// Mocks generated by Mockito 5.4.2 from annotations
// in bikecare/test/lib/src/config/presentation/widgets/views/bottom_navigation_bar_place_holder_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bikecare/src/config/presentation/cubits/cubit/routing_cubit.dart'
    as _i2;
import 'package:bloc/bloc.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRoutingState_0 extends _i1.SmartFake implements _i2.RoutingState {
  _FakeRoutingState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RoutingCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutingCubit extends _i1.Mock implements _i2.RoutingCubit {
  @override
  _i2.RoutingState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeRoutingState_0(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeRoutingState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.RoutingState);

  @override
  _i3.Stream<_i2.RoutingState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i2.RoutingState>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.RoutingState>.empty(),
      ) as _i3.Stream<_i2.RoutingState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void selectedNavigationBarItems(int? index) => super.noSuchMethod(
        Invocation.method(
          #selectedNavigationBarItems,
          [index],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void goToPage(String? path) => super.noSuchMethod(
        Invocation.method(
          #goToPage,
          [path],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushToPage(String? path) => super.noSuchMethod(
        Invocation.method(
          #pushToPage,
          [path],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.RoutingState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i4.Change<_i2.RoutingState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
